addcategory_product/addcategory_product/Controllers/AddcategorryController.cs
using addcategory_product.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using addcategory_product.viewmodels;
namespace addcategory_product.Controllers
{
    public class AddcategorryController : Controller
    {
        category_productsEntities db = new category_productsEntities();
        public ActionResult Index()
        {
            return View(db.tbl_category.ToList());
        }

        [HttpGet]

        //Create
        public ActionResult category()
        {
            return View();
        }

        [HttpPost]
        public ActionResult category(categoryviewmodel obj)
        {

            tbl_category t = new tbl_category();
            t.cat_name = obj.cat_name;
            db.tbl_category.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index");



            return View();
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {


            if (id == null)
            {

                return RedirectToAction("Index");
            }

           
            tbl_category t = db.tbl_category.Where(x => x.cat_id == id).SingleOrDefault();


            if (t == null)
            {
                return HttpNotFound();

            }

            return View(t);
        }

        [HttpPost]
        public ActionResult Edit(tbl_category std)
        {
          
            db.Entry(std).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");


            return View();
        }

        public ActionResult Delete(int? id)
        {
            if (id != null)
            {

                tbl_category cs = db.tbl_category.Find(id);
                db.tbl_category.Remove(cs);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");


            }
            return View();

        }

        public ActionResult Details(int? id)
        {

            tbl_category st = db.tbl_category.Find(id);

            return View(st);

        }
    }
}

addcategory_product/addcategory_product/Controllers/productsController.cs
using addcategory_product.Models;
using addcategory_product.viewmodels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace addcategory_product.Controllers
{
    public class productsController : Controller
    {
        category_productsEntities db = new category_productsEntities();
        // GET: products
        public ActionResult Index()
        {
            return View(db.products.ToList());
        }

        [HttpGet]
        public ActionResult addproduct()
        {

            List <tbl_category> List = db.tbl_category.ToList();
            ViewBag.list = new SelectList(List , "cat_id", "cat_name");

            return View();
        }

        [HttpPost]
        public ActionResult addproduct(productviewmodel obj , HttpPostedFileBase imgfile)
        {
            try
            {
                List<tbl_category> List = db.tbl_category.ToList();
                ViewBag.list = new SelectList(List, "cat_id", "cat_name");

                string s = uploadimgfile(imgfile);
                if (s.Equals("-1"))
                {
                    Response.Write("<script>alert('image upload failed...') <script>");
                }
                else
                {
                    product p = new product();
                    p.pro_name = obj.pro_name;
                    p.c_date = obj.c_date;
                    p.Mod_date = obj.Mod_date;
                    p.pro_description = obj.pro_description;
                    p.pro_image = s;
                    p.quanitity = obj.quanitity;
                    p.price = obj.price;
                    p.fk_tbl_category = obj.fk_tbl_category;
                    db.products.Add(p);
                    db.SaveChanges();
                    return RedirectToAction("Index");


                }

            }
            catch (Exception)
            {

                //throw;
            }
            return View();
        }


        public string uploadimgfile(HttpPostedFileBase file)
        {
            Random r = new Random();
            string path = "-1";
            int random = r.Next();
            if (file != null && file.ContentLength > 0)
            {
                string extension = Path.GetExtension(file.FileName);
                if (extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png"))
                {
                    try
                    {
                        path = Path.Combine(Server.MapPath("~/Content/images/"), random + Path.GetFileName(file.FileName));
                        file.SaveAs(path);
                        path = "~/Content/images/" + random + Path.GetFileName(file.FileName);

                    }
                    catch (Exception ex)
                    {

                        path = "-1";
                    }
                }
                else
                {
                    Response.Write("<script>alert('only png or jpeg or jpg format allow');<script>");

                }


            }

            return path;
        }



        public ActionResult Details(int? id)
        {

            product st = db.products.Find(id);

            return View(st);

        }






    }
}

addcategory_product/addcategory_product/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle"  data-toggle="dropdown">
                            Category
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Show Category", "Index", "Addcategorry")</li>
                            <li>@Html.ActionLink("Add Category", "category", "Addcategorry")</li>
                           
                        </ul>
                    </li>
                   
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            Product
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Show Product", "Index", "products")</li>
                            <li>@Html.ActionLink("Add Product", "addproduct", "products")</li>

                        </ul>
                    </li>                                   
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>